import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const exportItineraryToPDF = (itinerary) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Company branding
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246); // Blue
  doc.text('Travel CRM', 14, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text('Travel Itinerary', 14, 28);
  
  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 32, pageWidth - 14, 32);
  
  // Itinerary details
  let yPos = 42;
  
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  doc.text(itinerary.title || 'Untitled Itinerary', 14, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  
  // Customer info
  if (itinerary.customer) {
    doc.text(`Customer: ${itinerary.customer.name || 'N/A'}`, 14, yPos);
    yPos += 6;
    if (itinerary.customer.email) {
      doc.text(`Email: ${itinerary.customer.email}`, 14, yPos);
      yPos += 6;
    }
  }
  
  // Trip details
  if (itinerary.destination) {
    doc.text(`Destination: ${itinerary.destination}`, 14, yPos);
    yPos += 6;
  }
  
  if (itinerary.startDate && itinerary.endDate) {
    const start = new Date(itinerary.startDate).toLocaleDateString();
    const end = new Date(itinerary.endDate).toLocaleDateString();
    doc.text(`Duration: ${start} - ${end}`, 14, yPos);
    yPos += 6;
  }
  
  if (itinerary.travelers) {
    doc.text(`Travelers: ${itinerary.travelers}`, 14, yPos);
    yPos += 6;
  }
  
  yPos += 4;
  
  // Description
  if (itinerary.description) {
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text('Description:', 14, yPos);
    yPos += 6;
    
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    const splitDescription = doc.splitTextToSize(itinerary.description, pageWidth - 28);
    doc.text(splitDescription, 14, yPos);
    yPos += splitDescription.length * 5 + 6;
  }
  
  // Day-by-day itinerary
  if (itinerary.days && itinerary.days.length > 0) {
    // Check if we need a new page
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Daily Itinerary', 14, yPos);
    yPos += 10;
    
    itinerary.days.forEach((day, index) => {
      // Check if we need a new page
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }
      
      // Day header
      doc.setFillColor(59, 130, 246);
      doc.rect(14, yPos - 6, pageWidth - 28, 8, 'F');
      
      doc.setFontSize(12);
      doc.setTextColor(255, 255, 255);
      doc.text(`Day ${index + 1}${day.date ? ' - ' + new Date(day.date).toLocaleDateString() : ''}`, 16, yPos);
      yPos += 10;
      
      if (day.title) {
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.text(day.title, 16, yPos);
        yPos += 7;
      }
      
      if (day.description) {
        doc.setFontSize(9);
        doc.setTextColor(80, 80, 80);
        const splitDesc = doc.splitTextToSize(day.description, pageWidth - 32);
        doc.text(splitDesc, 16, yPos);
        yPos += splitDesc.length * 5 + 2;
      }
      
      // Activities
      if (day.activities && day.activities.length > 0) {
        yPos += 2;
        
        day.activities.forEach((activity, actIndex) => {
          // Check if we need a new page
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
          }
          
          doc.setFontSize(10);
          doc.setTextColor(0, 0, 0);
          doc.text(`• ${activity.time || ''} - ${activity.title}`, 20, yPos);
          yPos += 6;
          
          if (activity.description) {
            doc.setFontSize(9);
            doc.setTextColor(100, 100, 100);
            const splitActivityDesc = doc.splitTextToSize(activity.description, pageWidth - 36);
            doc.text(splitActivityDesc, 24, yPos);
            yPos += splitActivityDesc.length * 4 + 2;
          }
          
          if (activity.location) {
            doc.setFontSize(8);
            doc.setTextColor(120, 120, 120);
            doc.text(`Location: ${activity.location}`, 24, yPos);
            yPos += 5;
          }
        });
      }
      
      yPos += 4;
    });
  }
  
  // Add footer to all pages
  const totalPages = doc.internal.pages.length - 1; // Exclude the first empty page
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // Footer line
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 282, pageWidth - 14, 282);
    
    // Page number
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      288,
      { align: 'center' }
    );
    
    // Footer text
    doc.text('Generated by Travel CRM', 14, 288);
    doc.text(new Date().toLocaleDateString(), pageWidth - 14, 288, { align: 'right' });
  }
  
  // Save the PDF
  const fileName = `Itinerary_${itinerary.title?.replace(/[^a-z0-9]/gi, '_') || 'Untitled'}_${Date.now()}.pdf`;
  doc.save(fileName);
};

// Export booking confirmation PDF
export const exportBookingConfirmationToPDF = (booking) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246);
  doc.text('Travel CRM', 14, 20);
  
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text('Booking Confirmation', 14, 32);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 36, pageWidth - 14, 36);
  
  let yPos = 46;
  
  // Booking reference
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Booking Reference: ${booking.reference || 'N/A'}`, 14, yPos);
  yPos += 8;
  
  doc.text(`Status: ${booking.status || 'N/A'}`, 14, yPos);
  yPos += 12;
  
  // Customer details
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Customer Details', 14, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  if (booking.customer) {
    doc.text(`Name: ${booking.customer.name || 'N/A'}`, 14, yPos);
    yPos += 6;
    doc.text(`Email: ${booking.customer.email || 'N/A'}`, 14, yPos);
    yPos += 6;
    if (booking.customer.phone) {
      doc.text(`Phone: ${booking.customer.phone}`, 14, yPos);
      yPos += 6;
    }
  }
  yPos += 6;
  
  // Trip details
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Trip Details', 14, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  if (booking.destination) {
    doc.text(`Destination: ${booking.destination}`, 14, yPos);
    yPos += 6;
  }
  
  if (booking.startDate && booking.endDate) {
    const start = new Date(booking.startDate).toLocaleDateString();
    const end = new Date(booking.endDate).toLocaleDateString();
    doc.text(`Travel Dates: ${start} - ${end}`, 14, yPos);
    yPos += 6;
  }
  
  if (booking.travelers) {
    doc.text(`Number of Travelers: ${booking.travelers}`, 14, yPos);
    yPos += 6;
  }
  yPos += 6;
  
  // Payment information
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Payment Information', 14, yPos);
  yPos += 8;
  
  // Payment table
  const paymentData = [
    ['Total Amount', `$${booking.totalAmount?.toFixed(2) || '0.00'}`],
    ['Amount Paid', `$${booking.amountPaid?.toFixed(2) || '0.00'}`],
    ['Balance Due', `$${(booking.totalAmount - booking.amountPaid)?.toFixed(2) || '0.00'}`],
  ];
  
  doc.autoTable({
    startY: yPos,
    head: [['Description', 'Amount']],
    body: paymentData,
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
    margin: { left: 14, right: 14 },
  });
  
  yPos = doc.lastAutoTable.finalY + 10;
  
  // Footer
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 282, pageWidth - 14, 282);
  
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Travel CRM', 14, 288);
  doc.text(new Date().toLocaleDateString(), pageWidth - 14, 288, { align: 'right' });
  
  // Save
  const fileName = `Booking_${booking.reference?.replace(/[^a-z0-9]/gi, '_') || 'Confirmation'}_${Date.now()}.pdf`;
  doc.save(fileName);
};

export default {
  exportItineraryToPDF,
  exportBookingConfirmationToPDF,
};
